### ISSUE TITLE
Support resources object with multiple resource types?

### ISSUE THREAD

**Issue by jmeas** [jmeas/redux-resource#259]
Right now, you pass resources like so:

```js
{
  resourceName: 'books',
  resources: [bookOne, bookTwo],
  ...someStuff
}
```

This works well for the built-in action types, which only support one resource at a time (i.e.; you can only read books, but not books _and_ comments at the same time).

For multiple resources in a single request, the guidelines have been to write a plugin, which I think makes sense. There are so many different ways to support relationships and compound documents that I don't think it's possible for us to write one solution that works for every use-case in this library.

With that said, there is a problem with the current approach, in that you can't always easily use the built-in reducer, such as when using normalizr (#257). The reason is because `redux-resource` really doesn't like it when you don't include `resources`, yet `normalizr`, and some other solutions, don't always make a distinction between the primary resource and "included" resources.

One way to better add support for these sorts of solutions, as well as other solutions (even JSON API, which does distinguish between the main data and others), would be to support this _additional_ format for actions:

```js
{
  resources: {
    books: [bookOne, bookTwo],
    authors: [authorOne, authorTwo]
  },
  ...someStuff
}
```

This isn't making redux-resource any more opinionated, I think. It just makes it easier to write plugins to support JSON API or normalizr. It would also be backwards compatible.

The downside to this approach is that it makes it a little harder for folks writing plugins. They need to worry about these two formats, which could be annoying. I'd probably want to add a utility that maps an action to a common format for plugins to use.

What do folks think?

//cc @sprjr @marlonpp @tbranyen @jcrben @ianmstew @chrisdhanaraj ?

**Comment by ianmstew** [comment]
First a quick question:

> `redux-resource` really doesn't like it when you don't include `resources`, yet `normalizr`, and some other solutions, don't always make a distinction between the primary resource and "included" resources.

Could you expand on this?  I'm not sure how lacking a distinction between primary and included is connected to potentially not including `resources` in a given redux-resource action.

Thoughts:

This suggestion makes a lot of sense to me.  Yes, it permits the ability to write to multiple slices in one action allowing them to be more "global," but I think that is desirable for similar reasons as to why Redux actions are global--the need for a single event to possibly impact multiple slices.

My favorite part of the proposed API is that the "object" version of `resources` is a generalized version of the `{ resourceName : String, resources : Array }` object in a way that makes it more flexible without losing specificity.  In other words, I see the current API (`resources` array) as a special case of the proposed API.  In terms of plugin authors, transforming consistently to the new API makes sense given the observation above, that it's the general case.

The only complexity that the new API opens up is that resources are no longer 1:1 with a `resourceName`, but that is acceptable philosophically since it's a parallel complexity to common resourceful HTTP endpoints after which redux-resource is designed.  The added complexity _does_ open up a couple questions in my mind, however (not blocking, just details to consider):

* How do returned "secondary" models affect the metadata of their corresponding slices?
* Will their be some sanity checking checking that all returned resource keys exist as stores?

**Comment by jmeas** [comment]
The issue with this proposal is that it doesn't differentiate the primary response from the included data. Without this, you lose a ton of information. A better proposal that still differentiates the primary resource has been made over at #261 

I'll still keep this open, since I'm still thinking about this problem. Feel free to include any other thoughts or comments 🤔

**Comment by jmeas** [comment]
Alright, I thought more about it and I'm thinking I should close this out in favor of #261 , which avoids the issue of awkwardness around specifying the primary resource inherent to this proposal.
